#! /bin/sh
### BEGIN INIT INFO
# Provides:          godaemonsample
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example godaemon service template
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d. Please put a nice description here.
### END INIT INFO

# You must change the fields above: Example, Short-Description and Description.

# Service script template for godaemon services - based on the debian skeleton
# init script so it follows system conventions.
# Godaemon is configured by this script to:
# - Log output to <name>.log
# - Restart <name> if it fails (with safety throttle)
# Please look for MODIFY and alter the lines as instructed for your service.
# Author: Michael Nixon

PATH=/sbin:/usr/sbin:/bin:/usr/bin

# MODIFY: Please change this to the name of the service that is being run with
# godaemon, for example "MyService"
DESC="Godaemon service name"

# MODIFY: Change this to the name of the program that godaemon is running
NAME=testdaemon

# MODIFY: Change this to the full path of your program directory, which must
# contain a copy of godaemontask and your program
DAEMON=/mypath/godaemontask

# MODIFY: This must match the full path of this script.
SCRIPTNAME=/etc/init.d/myservice

# PLEASE DONT CHANGE ANYTHING BELOW HERE

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	$DAEMON start -rl $NAME
	RETVAL="$?"
	[ "$RETVAL" = 0 ] && return 0
	return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	$DAEMON stop $NAME
	RETVAL="$?"
	[ "$RETVAL" = 0 ] && return 2
	return 0
}

#
# Function that reloads the daemon/service
#
do_reload()
{
	# Return
	#   0 if daemon has been reloaded
	#   other if a failure occurred
	$DAEMON reload $NAME
	RETVAL="$?"
	return $RETVAL
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
  $DAEMON status $NAME
  case "$?" in
    1) log_failure_msg "$NAME is not running" && return 1 ;;
    0) log_success_msg "$NAME is running" && return 0 ;;
  esac
	;;
  reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	log_daemon_msg "Reloading $DESC" "$NAME"
	do_reload
	log_end_msg $?
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
